config/routes.rb
Myapp::Application.routes.draw do
  get "home/index"

root to: 'home#index'
resources :reports

end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
  end

  def show
  end

  def edit
  end

  def insurance_company
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="large-12 columns">
  <div id="login" class="large-4 large-centered columns">
  	<h4>Please Login</h4>
  	<label>
      <input type="text" placeholder="username" />
    </label>
    <label>
      <input type="text" placeholder="password" />
    </label>
    <a href="reports/" class="button radius round">Submit</a>
  </div>
</div>
<ol class="joyride-list" data-joyride>
  <li data-text="Next" data-options="tip_location: top">
    <p>Welcome to the Hazard Assessment Tool walkthrough. Click next at the bottom of the windows to proceed</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <%= image_tag("hat.png") %>
    <p>This is the homepage of a custom Nexus 7 tablet. It limits users to only these five apps making it extremely simple to use. Let's take a tour of all the tools in the order they will be used.</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <%= image_tag("app_calendar.png") %>
    <p>The calendar will contain all of the firefighter's appointments. Utilizing google calendar allows us to change appointments remotely and instantly syncs the changes with the tablet.</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <%= image_tag("app_appointment.png") %>
    <p>Each appointment will contain all the neccessary client information and in addition, when the address is tapped on it will open the maps application.</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <%= image_tag("app_map-1.png") %>
    <p>This allows the firefighter to easily utilize google maps to locate the next clients location.</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <%= image_tag("app_map-2.png") %>
    <p>Tapping navigate will begin the navigation process with no manual data entry necessary.</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <%= image_tag("app_homepage.png") %>
    <p>After arrival the firefighter begins the assessment by running the report app.</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <%= image_tag("app_homeowner-info.png") %>
    <p>The firefighter then enters in the neccessary information. (Eventually this could be accomplished automatically using the google calendar API).</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <%= image_tag("app_script.png") %>
    <p>A dropdown menu contains pre-built scripts that the firefighter can utilize for common conditions.</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <%= image_tag("app_script-in.png") %>
    <p>Tapping the camera button will open the device camera.</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <%= image_tag("app_voice.png") %>
    <p>We even utilize google's speech recognition technology so that the firefighter need not type at all. </p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <%= image_tag("app_summary.png") %>
    <p>When the report is finished, this page can be used to make corrections in the field.</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <p>This app is fully functioning and is ready for field testing. The report that you will see in the web app was created using the hazard assessment tool.</p>
  </li>
  <li data-text="Next" data-options="tip_location: top">
    <h4>The web app</h4>
    <p>These boxes will guide you through the web app.</p>
  </li>
  <li data-button="End">
    <p>There is no need to enter a username and password, just click submit.</p>
  </li>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Firestorm || WFHA" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  
  <header>
    <%= image_tag("header_bg.png") %>
  </header>

    <%= yield %>


    <%= javascript_include_tag "application" %>
  <div id="footer">
    <%= image_tag("footer_bg.jpg") %>
  </div>
  </body>
</html>

app/views/reports/edit.html.erb
<div style="margin-top: 3em" class="large-12 columns">
  <div id="company_list" style="background-color: grey" class="row">
  	<div id="jacob" style="padding-top: 2em" class="large-6 columns">
      <h4>Jacob Lee</h4>
      <h4>kyrios01@gmail.com</h4>
      <h4>1702 Carvell Drive</h4>
      <h4>Nashville, TN 37203</h4>
      <h4>USAA</h4>
  	</div>
  	<div id="report" class="large-6 columns">
  		A
  	</div>
  </div>
  <div style="background-color: grey; margin-bottom: 3em" class="row">
    <div class="large-12 columns">
      <?xml version='1.0' encoding='Utf-8' standalone='yes' ?>
      <Reports>
        <div class="large-7 large-centered columns">
          <div id="condition">
            <%= image_tag("../firestorm20140703_133532556027013.jpg") %>
            <p> - Roof is in good condition and is unlikely to contribute risk.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_133603-554029633.jpg") %>
            <p> - Roof vents are all properly screened and are unlikely to contribute risk.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_133708-1654158309.jpg") %>
            <p> - Roof contains combustible materials which could be ignited by embers.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <div id="orbit" class="orbit-container">
            <ul data-orbit data-options="pause_on_hover: false; animation: fade; animation_speed: 1000; timer_speed: 5000; slide_number: false; navigation_arrows: true">
              <li><%= link_to(image_tag("../firestorm20140703_1338042043194820.jpg"), report_path(0)) %></li>
              <li><%= link_to(image_tag("../firestorm20140703_133827445415983.jpg"), report_path(0)) %></li>
              <li><%= link_to(image_tag("../firestorm20140703_133901-1770452160.jpg"), report_path(0)) %></li>
            </ul>
            </div>
            <p> - Gutters contain combustible material which could be ignited by embers.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <div class="orbit-container">
            <ul data-orbit data-options="pause_on_hover: false; animation: fade; animation_speed: 1000; timer_speed: 5000; slide_number: false; navigation_arrows: true">
              <li><%= link_to(image_tag("../firestorm20140703_133935-1516054953.jpg"), report_path(0)) %></li>
              <li><%= link_to(image_tag("../firestorm20140703_1339581664560422.jpg"), report_path(0)) %></li>
            </ul>
            </div>
            <p> - Eaves are in good condition and is unlikely to contribute risk.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_134051253409149.jpg") %>
            <p> - Vents are above the minimum safety standard and further reduce risk to this structure.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_134115976365991.jpg") %>
            <p> - Eaves are clear of any combustible vegetation or debris.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_1341341247554092.jpg") %>
            <p> - Siding is in good condition and is unlikely to contribute risk.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_134207-142331382.jpg") %>
            <p> - Wall vents are above the minimum safety standard and further reduce risk to this structure.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_134250-204575660.jpg") %>
            <p> - Windows are in good condition and are unlikely to contribute risk.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_134410-1375303386.jpg") %>
            <p> - Clearance is exceptional and helps to reduce risk to this structure.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_134445-2130967777.jpg") %>
            <p> - Combustible materials exist within this zone which could be ignited by embers which would present significant risk the structure.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_134521-364613287.jpg") %>
            <p> - Defensible spacing is exceptional and helps to reduce risk to this structure.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_134605132403832.jpg") %>
            <p> - Area is clear of any significant combustible materials.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <div class="orbit-container">
            <ul data-orbit data-options="pause_on_hover: false; animation: fade; animation_speed: 1000; timer_speed: 5000; slide_number: false; navigation_arrows: true">
              <li><%= link_to(image_tag("../firestorm20140703_134638-1173033819.jpg"), report_path(0)) %></li>
              <li><%= link_to(image_tag("../firestorm20140703_13464823105241.jpg"), report_path(0)) %></li>
            </ul>
            </div>
             <p> - Structure is located near other homes that could potentially contribute a risk to the structure.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <div class="orbit-container">
            <ul data-orbit data-options="pause_on_hover: false; animation: fade; animation_speed: 1000; timer_speed: 5000; slide_number: false; navigation_arrows: true">
              <li><%= link_to(image_tag("../firestorm20140703_134722-1238853383.jpg"), report_path(0)) %></li>
              <li><%= link_to(image_tag("../firestorm20140703_134731-1049924090.jpg"), report_path(0)) %></li>
            </ul>
            </div>
            <p> - Access to the structure meets minimum standards for a type 3 fire engine.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_1348261087795518.jpg") %>
            <p>Hydrant is located nearby.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
          <div id="condition">
            <%= image_tag("../firestorm20140703_1349321194023081.jpg") %>
            <p>Home is located in a residential community and therefore is not subject to many of the risk factors associated with wildfire.</p>
            <%= link_to("Edit", report_path(0), class:"small button radius round") %>
            <%= link_to("Save", report_path(0), class:"small button radius round") %>
          </div>
        </div>
        <div class="large-12 columns">
  	      <div id="redzone" class="large-6 columns">
            <%= image_tag("redzone_area.jpg") %>
            <p>General area hazard...</p>
          </div>
          <div id="redzone" class="large-6 columns">
            <%= image_tag("redzone_site.jpg") %>
            <p>Site specific area hazard...</p>
        </div>
      </div>
      </Reports>
        <%= link_to("Approve Report", report_path(0), class:"medium button radius round", :id => "approve") %>
  	</div>
  </div>
</div>
<ol class="joyride-list" data-joyride>
  <li data-text="Next" data-options="tip_location: top">
    <p>This is the report page it will be automatically generated after the reports are uploaded from the field application.</p>
  </li>
  <li data-id="report" data-text="Next" data-options="tip_location: top">
    <p>This letter grade is purely for the homeowner. The letter grade will ONLY be an indicator of the effort of the homeowner to mitigate risk and is NOT indicative of actual risk, or lack of risk to the home. This will be automatically generated based on how many conditions are reported in the field.</p>
  </li>
  <li data-id="condition" data-text="Next" data-options="tip_location: top">
    <p>The edit and save buttons do not yet function.</p>
  </li>
  <li data-id="orbit" data-text="Next" data-options="tip_location: top">
    <p>Some Conditions will have multiple photos. Use the arrows to navigate.</p>
  </li>
  <li data-id="redzone" data-text="Next" data-options="tip_location: top">
    <p>This is just example data from Redzone which will be different once we are actually accessing their servers.</p>
  </li>
  <li data-id="approve" data-button="Back to top" data-options="tip_location: top">
    <p>Once the report is checked for errors this button will send the data to either the home owner, the insurance company, or both. They will be sent an email with a link to the report page and temporary login information.</p>
  </li>
  <li data-id="jacob" data-button="End" data-options="tip_location: top">
    <p>The final report will look nearly the same, excluding of course the save and edit buttons.</p>
  </li>
</ol>

app/views/reports/index.html.erb
<div class="large-12 columns">
  <div id="company_list" class="large-6 large-centered columns">  
    <ul id="company_list">
      <li><%= link_to(image_tag("firemansfund.jpg"), "show") %></li>
      </br>
      <li><%= link_to(image_tag("usaa.jpg"), "show") %></li>
      </br>
      <li><%= link_to(image_tag("statefarm.png"), "show") %></li>
      </br>
      <li><%= link_to(image_tag("libertymutual.jpg"), "show") %></li>
    </ul>
  </div>
</div>
<ol class="joyride-list" data-joyride>
  <li data-button="End">
    <p>Click any of the logos to go to the example report list, this page is just to illustrate that we can keep reports separate per insurance company.</p>
  </li>
</ol>

app/views/reports/show.html.erb
<div class="large-12 columns">
  <div style="background-color: grey; margin-top: 3em" class="large-6 large-centered columns">
    <ul id="company_list">
  	  <li><%= link_to("Jacob Lee, Sun July 6 11:32:22 2014", "reports/edit") %></li>
  	  <li><%= link_to("Jacob Lee, Sun July 6 11:32:22 2014", "reports/edit") %></li>
  	  <li><%= link_to("Jacob Lee, Sun July 6 11:32:22 2014", "reports/edit") %></li>
  	  <li><%= link_to("Jacob Lee, Sun July 6 11:32:22 2014", "reports/edit") %></li>
  	  <li><%= link_to("Jacob Lee, Sun July 6 11:32:22 2014", "reports/edit") %></li>
  	  <li><%= link_to("Jacob Lee, Sun July 6 11:32:22 2014", "reports/edit") %></li>
  	  <li><%= link_to("Jacob Lee, Sun July 6 11:32:22 2014", "reports/edit") %></li>
  	  <li><%= link_to("Jacob Lee, Sun July 6 11:32:22 2014", "reports/edit") %></li>
  	  <li><%= link_to("Jacob Lee, Sun July 6 11:32:22 2014", "reports/edit") %></li>
    </ul>
  </div>
</div>
<ol class="joyride-list" data-joyride>
  <li data-button="End">
    <p>This page will contain a list of all the reports pertaining to the aforementioned insurance company. These will only be reports that have not yet been approved. When a firefighter uploads reports from the field they will end up here. Click any one of them to see the report example.</p>
  </li>
</ol>